# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Pravila.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(520, 430)
        Form.setStyleSheet("background-color:rgb(0, 170, 255)")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(180, 20, 171, 51))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label.setFont(font)
        self.label.setStyleSheet("background-color:rgb(170, 255, 255)")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(110, 80, 311, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(60, 110, 421, 61))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.label_3.setToolTipDuration(-1)
        self.label_3.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_3.setTextFormat(QtCore.Qt.AutoText)
        self.label_3.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(80, 180, 381, 241))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "Правила игры"))
        self.label_2.setText(_translate("Form", "1. Цель игры – набрать больше очков. "))
        self.label_3.setText(_translate("Form", "<html><head/><body><p>2. Конец игры – игра заканчивается тогда, </p><p>когда игрок дошел до нижней границы игрового поля. </p></body></html>"))
        self.label_4.setText(_translate("Form", "<html><head/><body><p align=\"center\">3. На игровом поле расположены шары разных</p><p align=\"center\"> цветов. За раннее расположены на выбранной </p><p align=\"center\">игроком уровне сложности. Игроку нужно</p><p align=\"center\"> уничтожить шары одного цвета, стреляя шаром </p><p align=\"center\">того же цвета, чтобы их было по три и более.</p><p align=\"center\"> После одного выстрела цвет у шара меняется. </p><p align=\"center\">Игра заканчивается тогда, когда игрок дошел до </p><p align=\"center\">нижней границы игрового поля. </p></body></html>"))
